### model
model_name_or_path: Qwen/Qwen2.5-1.5B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full

### dataset
dataset: wmt14_en_de_train
template: qwen
cutoff_len: 512
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/wmt/full/en-de
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]
dataset_dir: ../data/wmt14
### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
pure_bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
eval_dataset: wmt14_en_de_valid
per_device_eval_batch_size: 16
eval_strategy: steps
eval_steps: 100
save_total_limit: 3
load_best_model_at_end: True
metric_for_best_model: eval_loss
save_only_model: true